### ISSUE TITLE
giblib error: Saving to file ... failed

### ISSUE THREAD

**Issue by dimaqq** [lucy/scrot#1]
Hey, original scrot has this confusing error when it fails to understand file extension and consequently image format:

``` bash
[dima@bmg Downloads]$ scrot -s test.png.1
giblib error: Saving to file test.png.1 failed

[dima@bmg Downloads]$ scrot -s test.png
[dima@bmg Downloads]$   # ok
```

this error can be found in ubuntu reports in 2010 already, and it's present in arch linux up to date.

I don't know if your repo has this problem

Would be nice to have that fixed anyhow :)

**Comment by lucy** [comment]
I think I would have to fork giblib for that as it's also by the scrot author, and the last release was in 2004. Hopefully someone writes a new tool for this eventually.
